name: Draft New Release

on:
  push:
    branches:
      - main

permissions:
  contents: write     # needed to create/update releases
  id-token: write     # for semantic-release auth if required
  packages: write     # for any semantic-release plugins that touch packages

jobs:
  prepare-and-draft:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Get short (7 characters long) commit SHA code
      - name: Extract short SHA
        id: extract_sha
        shell: bash
        run: |
          full_sha="${{ github.sha }}"
          short_sha="${full_sha:0:7}"
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT

      # 3. Extract only the commit description (body)
      - name: Extract commit description
        id: extract_desc
        shell: bash
        run: |
          desc=$(git log -1 --pretty=%B | tail -n +3)
          echo "commit_description<<EOF" >> $GITHUB_OUTPUT
          echo "$desc" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 4. Install Clang (moved up as it's needed before building)
      - name: Install Clang Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      # 5. Run ./build.sh -clang to build with clang and display logs
      - name: Build with Clang and Display Logs
        run: |
          chmod +x ./build.sh # Make the build script executable
          # Run the build script, capture its output, and tee it to a log file
          ./build.sh -clang 2>&1 | tee build_output.log
          BUILD_EXIT_CODE=${PIPESTATUS[0]} # Get the exit code of ./build.sh

          echo "--- Detailed Build Output from ./build.sh ---"
          cat build_output.log # Display the full captured output to the GitHub Actions console
          echo "---------------------------------------------"

          # Fail the GitHub Actions step if the build script itself failed
          if [ $BUILD_EXIT_CODE -ne 0 ]; then
            echo "##[error]The build script (./build.sh -clang) failed with exit code $BUILD_EXIT_CODE."
            exit $BUILD_EXIT_CODE
          fi

      # 6. Run ./dist/gha/packagezip from the base directory
      - name: Package Binaries for UNIX
        run: ./dist/gha/packagezip # Assumes this executable is in dist/gha and creates tread-bin-UNIX.zip in the root

      # 7. Create the draft pre-release and attach asset
      - name: Create Draft GitHub Release with Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract_sha.outputs.short_sha }}
          name: Pre-release v${{ steps.extract_sha.outputs.short_sha }}
          draft: true
          prerelease: true
          body: |
            Pre-release v${{ steps.extract_sha.outputs.short_sha }}
            **Triggered by committer:** @${{ github.actor }}

            ---

            # What's changed?
            ${{ steps.extract_desc.outputs.commit_description }}
          files: |
            ./tread-bin-UNIX.zip # Attach the generated zip file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
